{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{let approval_content=$collaboration_item.content
     $group=fetch('content','object', hash('object_id', $approval_content.group_id))}
{set-block scope=root variable=subject}{'[%sitename] Membership registration for group "%groupname" needs your approval'
                                        |i18n( "extension/membership/collaboration",,
                                               hash( '%sitename', ezini( "SiteSettings", "SiteURL" ),
                                                     '%groupname', $group.name|wash ) )}{/set-block}
{'You have requested to join the group "%groupname" at %sitename.
Your request is waiting for approval. To view the status of your request or to add a comment, visit the URL below.'
 |i18n( 'extension/membership/collaboration',,
        hash( '%sitename', ezini( "SiteSettings", "SiteURL" ),
              '%groupname', $group.name|wash ) )}
http://{ezini( "SiteSettings", "SiteURL" )}/collaboration/item/full/{$collaboration_item.id}

{"If you do not wish to continue receiving these notifications,
change your settings at:"|i18n( 'design/standard/notification' )}
http://{ezini( "SiteSettings", "SiteURL" )}/notification/settings/

--
{"%sitename notification system"
 |i18n( 'extension/membership/collaboration',,
        hash( '%sitename', ezini( "SiteSettings", "SiteURL" ) ) )}
{/let}